# Generated by Django 5.0.6 on 2024-05-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redeadmin', '0002_servicos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicos_Comerciais',
        ),
        migrations.DeleteModel(
            name='Servicos_Sociais',
        ),
        migrations.DeleteModel(
            name='Servicos_tecnicos',
        ),
    ]
