# Generated by Django 5.0.6 on 2024-05-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeadmin', '0004_servicos_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicos',
            old_name='preco',
            new_name='preco_maximo',
        ),
        migrations.AddField(
            model_name='servicos',
            name='preco_minimo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
