# Generated by Django 4.2.13 on 2024-05-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeadmin', '0005_rename_preco_servicos_preco_maximo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='porcetagem',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicos',
            name='preco_maximo',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='preco_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
