# Generated by Django 5.0.6 on 2024-05-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_solicitacao', models.IntegerField()),
                ('nome_servico', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1200)),
                ('quantidade', models.IntegerField()),
                ('Id_Individuo', models.IntegerField()),
            ],
        ),
    ]
